task: python_logic
dataset_path: json
dataset_kwargs:
  data_files:
    test: eval_runner/custom_task/python_logic.jsonl
test_split: test
output_type: multiple_choice
doc_to_text: "Question: {{question}}\nA) {{choices[0]}}\nB) {{choices[1]}}\nC) {{choices[2]}}\nD) {{choices[3]}}\nAnswer:"
doc_to_target: "{{answer}}"
doc_to_choice: "{{choices}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
